server:
  port: 8888

spring:
  application:
    name: config-service
  rabbitmq:
    host: 127.0.0.1
    port: 5672
    username: guest
    password: guest
  cloud:
    config:
      server:
        git:
          uri: https://github.com/snowlight-aemt/spring-cloud-git-repository
          username: st.passage@gmail.com
          password: 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

management:
  endpoints:
    web:
      exposure:
        include: refresh,health,beans,httptrace,busrefresh